### ISSUE TITLE
font: 20px Arial; VS font-family: Arial; font-size: 20px;

### ISSUE THREAD

**Issue by montyanderson** [mdo/css-perf#18]
If you could do a test, that'd be great.

**Comment by mdo** [comment]
I'm not really testing things here anymore—I think most of the rather unscientific tests I've run have shown that simple changes like this don't really matter much. Plus this is rather similar to the `background` shorthand tests I ran. Personally I'd go with the latter—separate properties—since that's more specific and easier to maintain.

**Comment by montyanderson** [comment]
Okay, thanks for the advise.
